/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.ConexionBD;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import operaciones.Dueno;

/**
 *
 * @author vanes
 */
public class FormIngresoDueno extends javax.swing.JFrame {
    
    Dueno objDueno = new Dueno();
    ConexionBD objConectar = new ConexionBD();

    /**
     * Creates new form FormIngresoDueno
     */
    public FormIngresoDueno() {
        initComponents();
        ConexionBD.getConexion();
    }
    
    private void limpiarForm() {
        inputNombre.setText("");
        inputApellido.setText("");
        inputEdad.setText("");
        inputFem.setSelected(false);
        inputMasc.setSelected(false);
        
        //limpiar datos mascota
        inputNombreMascota.setText("");
        inputMacho.setSelected(false);
        inputHembra.setSelected(false);
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtnSexo = new javax.swing.ButtonGroup();
        btnGrupoSexoMascota = new javax.swing.ButtonGroup();
        formAgregar = new javax.swing.JButton();
        inputNombre = new javax.swing.JTextField();
        inputApellido = new javax.swing.JTextField();
        inputEdad = new javax.swing.JTextField();
        inputNombreMascota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputFem = new javax.swing.JRadioButton();
        inputMasc = new javax.swing.JRadioButton();
        inputHembra = new javax.swing.JRadioButton();
        inputMacho = new javax.swing.JRadioButton();
        btnLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formAgregar.setText("Agregar");
        formAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formAgregarActionPerformed(evt);
            }
        });

        inputNombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreMascotaActionPerformed(evt);
            }
        });

        jLabel1.setText("DATOS MASCOTA");

        jLabel2.setText("FORMULARIO DE INGRESO");

        jLabel3.setText("DATOS DUEÑO");

        grupoBtnSexo.add(inputFem);
        inputFem.setText("Femenino");
        inputFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFemActionPerformed(evt);
            }
        });

        grupoBtnSexo.add(inputMasc);
        inputMasc.setText("Masculino");
        inputMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMascActionPerformed(evt);
            }
        });

        btnGrupoSexoMascota.add(inputHembra);
        inputHembra.setText("Hembra");
        inputHembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHembraActionPerformed(evt);
            }
        });

        btnGrupoSexoMascota.add(inputMacho);
        inputMacho.setText("Macho");
        inputMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMachoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jButton1.setText("Listar Dueños y Mascotas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Edad:");

        jLabel7.setText("Nombre Mascota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(inputNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(inputHembra)
                                .addGap(45, 45, 45)
                                .addComponent(inputMacho))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(inputFem)
                                .addGap(18, 18, 18)
                                .addComponent(inputMasc))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formAgregar))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMasc)
                    .addComponent(inputFem))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHembra)
                    .addComponent(inputMacho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formAgregarActionPerformed
        // TODO add your handling code here:
        
       objDueno.setNombre(inputNombre.getText());
       objDueno.setApellido(inputApellido.getText());
       objDueno.setEdad(Byte.parseByte(inputEdad.getText()));
       
       objDueno.getObjMascota().setNombreMascota(inputNombreMascota.getText());
       
       //TODO agregar mensaje de confirmacion
       objDueno = objDueno.ingresarNuevoDueno(objDueno);
       
       if (objDueno.isEsExito()) {
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente.");
            System.out.println(objDueno.getMensaje());
        } else {
           JOptionPane.showMessageDialog(null, "ERROR DATOS NO INGRESADOS");
            System.out.println("Excepcion Capturada: "+objDueno.getMensaje());
            System.out.println("");
        }
       
    }//GEN-LAST:event_formAgregarActionPerformed

    private void inputNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreMascotaActionPerformed

    private void inputFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFemActionPerformed
        // TODO add your handling code here:
        if(inputFem.isSelected()) {
            objDueno.setSexo('F');
        }
    }//GEN-LAST:event_inputFemActionPerformed

    private void inputMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMascActionPerformed
        // TODO add your handling code here:
        if(inputMasc.isSelected()) {
            objDueno.setSexo(('M'));
        }
    }//GEN-LAST:event_inputMascActionPerformed

    private void inputHembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHembraActionPerformed
        // TODO add your handling code here:
        if(inputHembra.isSelected()) {
            objDueno.getObjMascota().setSexoMascota('H');
        }
    }//GEN-LAST:event_inputHembraActionPerformed

    private void inputMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMachoActionPerformed
        // TODO add your handling code here:
        if(inputMacho.isSelected()) {
            objDueno.getObjMascota().setSexoMascota('M');
        }
    }//GEN-LAST:event_inputMachoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarForm();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ListarDuenos objListarDuenos = new ListarDuenos();
        objListarDuenos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIngresoDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIngresoDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIngresoDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIngresoDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIngresoDueno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupoSexoMascota;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton formAgregar;
    private javax.swing.ButtonGroup grupoBtnSexo;
    private javax.swing.JTextField inputApellido;
    private javax.swing.JTextField inputEdad;
    private javax.swing.JRadioButton inputFem;
    private javax.swing.JRadioButton inputHembra;
    private javax.swing.JRadioButton inputMacho;
    private javax.swing.JRadioButton inputMasc;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombreMascota;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
